### ISSUE TITLE
[error] stash한 작업내용을 다시 불러오지 못하는 현상

### ISSUE THREAD

**Issue by cloudysunny25** [YooDonggyu/kosta179-final-studit#8]
- **Issue 위치**: 회원탈퇴 기능 구현부를 push하기 전 stash했을 때
- **문제점**: stash 후 기존 작업 내용 일부가 사라짐. stash한 내용을 조회는 할 수 있지만 저장소에는 남아있지 않아 프로젝트에 다시 불러올 수 없는 상태가 됨.
- **원인**:  

- **담당자**
 송용준, 유동규, 김유란

**Comment by YooDonggyu** [comment]
unstaging 상태의 파일들을 staging으로 옮긴 후 stash 작업하여 문제 해결
